util: Use `constexpr` in `LockedPool` definitions
Expression decomposition in `BOOST_TEST` and the framework introduced
later binds the operand to a `const T&`, which must have the definition.
Without this there is the following linker error:

```
/bitcoin-core/bitcoin/src/test/allocator_tests.cpp:209:(.text+0x77d6): undefined reference to `LockedPool::ARENA_SIZE'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```