net: Make `AddressPosition` comparitor `const`
Needed to use `==` operator in tests. Full error output:

```
/bitcoin-core/bitcoin/src/test/util/framework.h:295:18: error: invalid operands to binary expression ('const AddressPosition' and 'const AddressPosition')
  295 |     DECOMPOSE_OP(==, std::cmp_equal)
      |     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/bitcoin-core/bitcoin/src/test/util/framework.h:290:53: note: expanded from macro 'DECOMPOSE_OP'
  290 |             btc_test_result = static_cast<bool>(lhs op rhs);                                                   \
      |                                                 ~~~ ^  ~~~
/bitcoin-core/bitcoin/src/test/addrman_tests.cpp:817:27: note: in instantiation of function template specialization 'framework::CapturedExpression<AddressPosition>::operator==<AddressPosition>' requested here
  817 |     BOOST_CHECK(addr_pos1 == addr_pos2);
      |                           ^
/bitcoin-core/bitcoin/src/addrman.h:76:10: note: candidate function not viable: 'this' argument has type 'const AddressPosition', but method is not marked const
   76 |     bool operator==(AddressPosition other) {
      |          ^
/bitcoin-core/bitcoin/src/addrman.h:76:10: note: candidate function (with reversed parameter order) not viable: 1st argument ('const AddressPosition') would lose const qualifier
   76 |     bool operator==(AddressPosition other) {
      |          ^          ~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[268/274] Building CXX object src/CMakeFiles/bitcoin_node.dir/init.cpp.o
```