crypto: Use `constexpr` to define output size
Using this constant in as a `const T&` requires a definition, else the
linker fails:

```
undefined reference to `CHMAC_SHA512::OUTPUT_SIZE'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```